/* ====================================================
   ALERTS MODULE — Independiente de otros módulos
   ==================================================== */

/* ── Cálculo de intervalo (km) según tipo de vehículo y mantenimiento ── */
function getAlertIntervalo(tipoVehiculo, tipoMantenimiento) {
  const tv = String(tipoVehiculo || '').toLowerCase();
  const isMoto = tv.includes('motocicleta') || tv === 'moto' || tv === 'motocicletas';
  const tm = String(tipoMantenimiento || '').toLowerCase();

  if (tm.includes('llanta delantera')) return 5000;
  if (tm.includes('llanta trasera')) return 10000;
  if (tm.includes('llanta')) return 35000;
  if (tm.includes('aceite')) return isMoto ? 1500 : 5000;
  return 0;
}

/* ── Próximo km de mantenimiento (siguiente múltiplo del intervalo) ── */
function getNextKm(currentKm, intervaloKm) {
  const km = parseFloat(currentKm) || 0;
  const it = parseFloat(intervaloKm) || 1;
  return (Math.floor(km / it) + 1) * it;
}

/* ── Semáforo por km restantes ── */
function getAlertSeverity(a) {
  const remaining = parseFloat(a.remainingKm) || (parseFloat(a.nextKm) - parseFloat(a.currentKm)) || 0;
  if (a.estado === 'Completada') return 'completed';
  if (remaining < 0) return 'critical';
  if (remaining < 500) return 'danger';
  if (remaining <= 1000) return 'warning';
  return 'success';
}

function severityInfo(sev) {
  return {
    success:  { color:'green', label:'Verde',   css:'sev-green',  icon:'🟢' },
    warning:  { color:'yellow',label:'Amarillo',css:'sev-yellow', icon:'🟡' },
    danger:   { color:'red',   label:'Rojo',    css:'sev-red',    icon:'🔴' },
    critical: { color:'red',   label:'Crítico', css:'sev-critical',icon:'⛔' },
    completed:{ color:'green', label:'Completada', css:'sev-green', icon:'✅' },
    info:     { color:'blue',  label:'Info',    css:'sev-blue',   icon:'🔵' },
  }[sev] || { color:'blue', label:'Info', css:'sev-blue', icon:'🔵' };
}

function getEstados() { return ['Pendiente','Próxima','Vencida','Completada']; }
function getTiposVehiculo() { return ['Motocicleta','Carro','Camión','Camioneta','Otro']; }
function getTiposMantenimiento() {
  return ['Cambio de llanta delantera','Cambio de llanta trasera','Cambio de llantas','Cambio de aceite'];
}

/* ====================================================
   ALERTS MODULE VIEW
   ==================================================== */
const AlertsModule = {
  filter: { vehiculo:'', usuario:'', area:'', departamento:'', localidad:'', tipoVehiculo:'', tipoMantenimiento:'' },
  _autoGenerated: false,

  render() {
    this.ensureFleetAlerts();
    const alerts = DB.getAlertas();

    const activas = alerts.filter(a => a.estado !== 'Completada');
    const proximas = activas.filter(a => {
      const rem = parseFloat(a.remainingKm) || (parseFloat(a.nextKm) - parseFloat(a.currentKm)) || 0;
      return rem >= 0 && rem < 500;
    });
    const vencidas = activas.filter(a => {
      const rem = parseFloat(a.remainingKm) || (parseFloat(a.nextKm) - parseFloat(a.currentKm)) || 0;
      return rem < 0;
    });
    const completadas = alerts.filter(a => a.estado === 'Completada');

    const fleetAssets = DB.getAssets();
    const withKm      = fleetAssets.filter(a => parseFloat(a.currentKm) > 0).length;
    const withHrs     = fleetAssets.filter(a => parseFloat(a.currentHours) > 0).length;
    const withInsp    = fleetAssets.filter(a => a.inspectionDate).length;
    const fleetHint   = fleetAssets.length === 0
      ? 'Registra activos en la sección Activos y las alertas de mantenimiento se generarán automáticamente.'
      : (!withKm && !withHrs && !withInsp)
        ? `Hay ${fleetAssets.length} activos registrados, pero ninguno tiene kilometraje, horas o fecha de inspección. Edita un activo en "Activos" para registrar su kilometraje, o crea una alerta manual.`
        : 'Las alertas de mantenimiento se generan automáticamente a partir del kilometraje de la flota.';

    return `
    <div class="page-header">
      <div class="page-header-left">
        <h2>🔔 Centro de Alertas</h2>
        <p>Registro y seguimiento independiente de mantenimientos</p>
      </div>
      <div class="page-header-right">
        <button class="btn btn-outline" onclick="AlertsModule.generateFleetAlerts()">⚡ Generar alertas</button>
        <button class="btn btn-primary" onclick="AlertsModule.openModal()">➕ Nueva Alerta</button>
      </div>
    </div>

    <div class="alert-summary-row" style="grid-template-columns:repeat(4,1fr)">
      <div class="alert-summary-card asc-info">
        <div class="asc-icon">📌</div>
        <div class="asc-info-text"><div class="asc-num">${activas.length}</div><div class="asc-label">Alertas Activas</div></div>
      </div>
      <div class="alert-summary-card asc-warning">
        <div class="asc-icon">⏰</div>
        <div class="asc-info-text"><div class="asc-num">${proximas.length}</div><div class="asc-label">Próximas (&lt;500 km)</div></div>
      </div>
      <div class="alert-summary-card asc-danger">
        <div class="asc-icon">🚨</div>
        <div class="asc-info-text"><div class="asc-num">${vencidas.length}</div><div class="asc-label">Vencidas</div></div>
      </div>
      <div class="alert-summary-card asc-success">
        <div class="asc-icon">✅</div>
        <div class="asc-info-text"><div class="asc-num">${completadas.length}</div><div class="asc-label">Completadas</div></div>
      </div>
    </div>

    <div class="card" style="margin-top:16px;padding:14px">
      <div class="filter-bar" style="display:flex;flex-wrap:wrap;gap:10px;">
        ${this.renderFilter('vehiculo', 'Vehículo', this.uniq(alerts, 'vehiculo'), this.filter.vehiculo)}
        ${this.renderFilter('usuario', 'Usuario', this.uniq(alerts, 'usuario'), this.filter.usuario)}
        ${this.renderFilter('area', 'Área', this.uniq(alerts, 'area'), this.filter.area)}
        ${this.renderFilter('departamento', 'Departamento', this.uniq(alerts, 'departamento'), this.filter.departamento)}
        ${this.renderFilter('localidad', 'Localidad', this.uniq(alerts, 'localidad'), this.filter.localidad)}
        ${this.renderFilter('tipoVehiculo', 'Tipo de vehículo', this.uniq(alerts, 'tipoVehiculo'), this.filter.tipoVehiculo)}
        ${this.renderFilter('tipoMantenimiento', 'Tipo de mantenimiento', this.uniq(alerts, 'tipoMantenimiento'), this.filter.tipoMantenimiento)}
        <button class="btn btn-outline btn-sm" onclick="AlertsModule.resetFilters()">✖ Limpiar</button>
      </div>
    </div>

    ${alerts.length === 0 ? `
    <div class="empty-state">
      <div class="empty-icon">🔔</div>
      <h3>Sin alertas registradas</h3>
      <p>${fleetHint}</p>
      <div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap;margin-top:8px">
        <button class="btn btn-primary" onclick="AlertsModule.openModal()">➕ Nueva Alerta</button>
        <button class="btn btn-outline" onclick="AlertsModule.generateFleetAlerts()">⚡ Generar desde la flota</button>
      </div>
    </div>` : `
    <div class="card" style="padding:0;margin-top:16px">
      <div class="table-wrapper">
        <table>
          <thead><tr>
            <th>Estado</th><th>Vehículo</th><th>Tipo</th><th>Km Actual</th>
            <th>Mantenimiento</th><th>Próximo Km</th><th>Restante</th><th>Fecha</th><th>Acciones</th>
          </tr></thead>
          <tbody id="alerts-table-body">${this.renderRows()}</tbody>
        </table>
      </div>
    </div>`}
    <div id="alert-modal-placeholder"></div>`;
  },

  uniq(alerts, key) {
    return [...new Set(alerts.map(a => (a[key]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'));
  },

  renderFilter(key, label, values, current) {
    return `
    <div style="min-width:170px">
      <label class="form-label" style="font-size:11px;margin-bottom:4px">${label}</label>
      <select class="form-control" onchange="AlertsModule.setFilter('${key}', this.value)">
        <option value="">Todos</option>
        ${values.map(v => `<option value="${v}" ${v === current ? 'selected':''}>${v}</option>`).join('')}
      </select>
    </div>`;
  },

  setFilter(key, val) {
    this.filter[key] = val;
    this.renderTable();
  },

  resetFilters() {
    this.filter = { vehiculo:'', usuario:'', area:'', departamento:'', localidad:'', tipoVehiculo:'', tipoMantenimiento:'' };
    App.navigate('alerts');
  },

  generateFromFleet() {
    const assets = DB.getAssets().filter(a => parseFloat(a.currentKm) > 0);
    if (!assets.length) return [];
    const today = new Date().toISOString().slice(0, 10);
    const seen  = new Set(DB.getAlertas().map(a => a.id));
    const out   = [];
    for (const a of assets) {
      const tipos = ['Cambio de aceite'];
      if (!String(a.type || '').toLowerCase().includes('motocicleta')) tipos.push('Cambio de llantas');
      for (const tipo of tipos) {
        const intervaloKm = getAlertIntervalo(a.type, tipo);
        if (!intervaloKm) continue;
        const nextKm      = getNextKm(a.currentKm, intervaloKm);
        const remainingKm = nextKm - parseFloat(a.currentKm);
        const estado      = remainingKm < 0 ? 'Vencida' : remainingKm < 500 ? 'Próxima' : 'Pendiente';
        const severity    = getAlertSeverity({ estado, remainingKm, nextKm, currentKm: a.currentKm });
        const id          = `flt_${a.id}_${tipo.toLowerCase().replace(/[^a-z0-9]+/g, '')}`;
        if (seen.has(id)) continue;
        seen.add(id);
        out.push({
          id, assetId: a.id, vehiculo: a.code || a.id, tipoVehiculo: a.type || '',
          currentKm: a.currentKm, tipoMantenimiento: tipo, fecha: today, estado,
          usuario: a.usuario || '', area: a.area || '', departamento: a.departamento || '',
          localidad: a.localidad || '', placa: a.plate || '', intervaloKm, nextKm, remainingKm, severity,
        });
      }
    }
    return out;
  },

  ensureFleetAlerts() {
    if (this._autoGenerated) return;
    this._autoGenerated = true;
    try { if (localStorage.getItem('fleet_alerts_auto') === '1') return; } catch {}
    if (DB.getAlertas().length > 0) return;
    try {
      const generated = this.generateFromFleet();
      if (generated.length) {
        DB.saveAlertas(generated);
        try { localStorage.setItem('fleet_alerts_auto', '1'); } catch {}
      }
    } catch (e) { console.error('[Alerts] No se pudieron generar alertas:', e); }
  },

  generateFleetAlerts() {
    const byId = new Map(DB.getAlertas().map(a => [a.id, a]));
    const generated = this.generateFromFleet();
    generated.forEach(g => { if (!byId.has(g.id)) byId.set(g.id, g); });
    DB.saveAlertas([...byId.values()]);
    App.navigate('alerts');
    showToast(`Generadas ${generated.length} alertas desde la flota`, 'success');
  },

  getFiltered() {
    const f = this.filter;
    return DB.getAlertas().filter(a => {
      if (f.vehiculo && a.vehiculo !== f.vehiculo) return false;
      if (f.usuario && a.usuario !== f.usuario) return false;
      if (f.area && a.area !== f.area) return false;
      if (f.departamento && a.departamento !== f.departamento) return false;
      if (f.localidad && a.localidad !== f.localidad) return false;
      if (f.tipoVehiculo && a.tipoVehiculo !== f.tipoVehiculo) return false;
      if (f.tipoMantenimiento && a.tipoMantenimiento !== f.tipoMantenimiento) return false;
      return true;
    });
  },

  renderTable() {
    const tbody = document.querySelector('#alerts-table-body');
    if (tbody) tbody.innerHTML = this.renderRows();
  },

  renderRows() {
    const list = this.getFiltered();
    return list.map(a => {
      const sev = getAlertSeverity(a);
      const si  = severityInfo(sev);
      const rem = parseFloat(a.remainingKm) || (parseFloat(a.nextKm) - parseFloat(a.currentKm)) || 0;
      return `
      <tr>
        <td><span class="sev-dot ${si.css}" title="${si.label}"></span></td>
        <td class="fw-700">${a.vehiculo || '—'}</td>
        <td class="text-sm">${a.tipoVehiculo || '—'}</td>
        <td class="text-sm">${a.currentKm ? fmtKm(a.currentKm) : '—'}</td>
        <td>${a.tipoMantenimiento || '—'}</td>
        <td class="fw-700">${a.nextKm ? fmtKm(a.nextKm) : '—'}</td>
        <td class="text-sm ${rem < 0 ? 'text-danger fw-700' : ''}">${rem >= 0 ? fmtKm(rem) : 'Excedido'}</td>
        <td class="text-sm">${fmtDate(a.fecha)}</td>
        <td>
          <div class="table-actions">
            <button class="btn btn-outline btn-icon btn-sm" title="Editar" onclick="AlertsModule.openModal('${a.id}')">✏️</button>
            ${a.estado !== 'Completada' ? `<button class="btn btn-outline btn-icon btn-sm" title="Completar" onclick="AlertsModule.toggleEstado('${a.id}')">✅</button>` : ''}
            <button class="btn btn-outline btn-icon btn-sm" title="Eliminar" onclick="AlertsModule.remove('${a.id}')">🗑️</button>
          </div>
        </td>
      </tr>`;
    }).join('');
  },

  /* ── Modal crear / editar ── */
  openModal(id = null) {
    const alert  = id ? DB.getAlertas().find(a => a.id === id) : null;
    const assets = DB.getAssets();
    const today  = new Date().toISOString().slice(0, 10);

    let selAsset = null;
    if (alert) {
      const code = String(alert.vehiculo || '').trim();
      selAsset = assets.find(a => a.code === code) || null;
    }

    const currentKm = selAsset ? selAsset.currentKm : (alert ? alert.currentKm : 0);
    const tipoMantenimiento = alert ? (alert.tipoMantenimiento || 'Cambio de aceite') : 'Cambio de aceite';
    const estado = alert ? (alert.estado || 'Pendiente') : 'Pendiente';
    const fecha  = alert ? (alert.fecha || today) : today;

    const tv = selAsset ? selAsset.type : (alert ? alert.tipoVehiculo : '');
    const preview = this.compute(selAsset ? selAsset.code : (alert ? alert.vehiculo : ''), tv, currentKm, tipoMantenimiento);

    const indicator = this.assetCard(selAsset, alert && !selAsset);

    showModal('alert-modal-placeholder', id ? '✏️ Editar Alerta' : '➕ Nueva Alerta', `
    <div class="form-grid">
      <div class="form-group" style="grid-column: span 2">
        <label class="form-label">Vehículo (buscar por código, placa, marca o modelo) *</label>
        <input type="text" class="form-control" id="al-asset-search" list="al-asset-list" placeholder="🔍 Escribe código, placa, marca o modelo..." value="${selAsset ? this.assetLabel(selAsset) : (alert ? alert.vehiculo : '')}" oninput="AlertsModule.onAssetChange()" onchange="AlertsModule.onAssetChange()">
        <datalist id="al-asset-list">
          ${assets.filter(a => a.code).map(a => `<option value="${this.assetLabel(a)}">${a.type}</option>`).join('')}
        </datalist>
        <input type="hidden" id="al-asset" value="${selAsset ? selAsset.id : ''}">
        <div id="al-asset-info">${indicator}</div>
      </div>
      <div class="form-group"><label class="form-label">Tipo de vehículo</label><input class="form-control" id="al-tipoVehiculo" value="${tv}" readonly style="background:var(--bg-secondary)"></div>
      <div class="form-group"><label class="form-label">Kilometraje actual *</label><input class="form-control" type="number" min="0" id="al-currentKm" value="${currentKm || 0}" oninput="AlertsModule.preview()"></div>
      <div class="form-group"><label class="form-label">Tipo de mantenimiento *</label>
        <select class="form-control" id="al-tipoMantenimiento" onchange="AlertsModule.preview()">
          ${getTiposMantenimiento().map(t => `<option value="${t}" ${tipoMantenimiento === t ? 'selected':''}>${t}</option>`).join('')}
        </select>
      </div>
      <div class="form-group"><label class="form-label">Fecha de registro *</label><input class="form-control" type="date" id="al-fecha" value="${fecha}"></div>
      <div class="form-group"><label class="form-label">Estado</label>
        <select class="form-control" id="al-estado">
          ${getEstados().map(s => `<option value="${s}" ${estado === s ? 'selected':''}>${s}</option>`).join('')}
        </select>
      </div>
      <div class="form-group"><label class="form-label">Usuario</label><input class="form-control" id="al-usuario" value="${selAsset ? selAsset.usuario : (alert ? alert.usuario : '')}" readonly style="background:var(--bg-secondary)"></div>
      <div class="form-group"><label class="form-label">Área</label><input class="form-control" id="al-area" value="${selAsset ? selAsset.area : (alert ? alert.area : '')}" readonly style="background:var(--bg-secondary)"></div>
      <div class="form-group"><label class="form-label">Departamento</label><input class="form-control" id="al-departamento" value="${selAsset ? selAsset.departamento : (alert ? alert.departamento : '')}" readonly style="background:var(--bg-secondary)"></div>
      <div class="form-group"><label class="form-label">Localidad</label><input class="form-control" id="al-localidad" value="${selAsset ? selAsset.localidad : (alert ? alert.localidad : '')}" readonly style="background:var(--bg-secondary)"></div>
    </div>
    <div class="card" style="margin-top:12px;padding:12px;background:var(--surface-2)">
      <div style="display:flex;gap:24px;flex-wrap:wrap">
        <div><span class="text-sm text-muted">Intervalo</span><div class="fw-700">${preview.intervaloKm ? fmtKm(preview.intervaloKm) : '—'}</div></div>
        <div><span class="text-sm text-muted">Próximo mantenimiento</span><div class="fw-700" id="al-nextkm">${preview.nextKm ? fmtKm(preview.nextKm) : '—'}</div></div>
      </div>
    </div>`,
    `<button class="btn btn-secondary" onclick="closeModal('alert-modal-placeholder')">Cancelar</button>
     <button class="btn btn-primary" onclick="AlertsModule.save('${id || ''}')">💾 Guardar</button>`);
  },

  assetLabel(a) {
    return [a.code, a.plate, [a.brand, a.model].filter(Boolean).join(' ')].filter(Boolean).join(' — ');
  },

  assetCard(a, warn = null) {
    if (a) {
      return `
      <div style="margin-top:10px;border:1px solid rgba(22,163,74,.45);border-radius:8px;padding:10px 12px;background:var(--surface-2)">
        <div class="fw-700 text-sm" style="color:#16a34a;margin-bottom:6px">✅ Activo Seleccionado</div>
        <div style="display:grid;grid-template-columns:auto 1fr;gap:2px 14px;font-size:12px">
          <span class="text-muted">Código:</span><span class="fw-700">${a.code || '—'}</span>
          <span class="text-muted">Placa:</span><span>${a.plate || '—'}</span>
          <span class="text-muted">Vehículo:</span><span>${[a.brand, a.model].filter(Boolean).join(' ') || '—'}</span>
          <span class="text-muted">Usuario:</span><span>${a.usuario || '—'}</span>
          <span class="text-muted">Área:</span><span>${a.area || '—'}</span>
          <span class="text-muted">Departamento:</span><span>${a.departamento || '—'}</span>
          <span class="text-muted">Localidad:</span><span>${a.localidad || '—'}</span>
        </div>
      </div>`;
    }
    const msg = warn
      ? '⚠️ Activo no encontrado en Registro de Activos. Selecciona un activo de la lista.'
      : 'Selecciona un activo de la lista para completar la información automáticamente.';
    return `
    <div style="margin-top:10px;border:1px dashed var(--border);border-radius:8px;padding:10px 12px;background:var(--surface-2);font-size:12px;color:var(--text-muted)">
      <span class="fw-700">Activo Seleccionado</span><br>${msg}
    </div>`;
  },

  onAssetChange() {
    const search = (document.getElementById('al-asset-search')?.value || '').trim();
    const info   = document.getElementById('al-asset-info');
    const prevId = document.getElementById('al-asset')?.value || '';
    const assets = DB.getAssets();
    const norm = s => String(s || '').toLowerCase().replace(/\s+/g, ' ').trim();
    const ns   = norm(search);
    const a = assets.find(x => x.code && norm(this.assetLabel(x)) === ns)
           || assets.find(x => x.code && norm(x.code) === ns) || null;
    const set = (eid, val) => { const e = document.getElementById(eid); if (e) e.value = val || ''; };

    if (a) {
      const isNew = a.id !== prevId;
      set('al-asset', a.id);
      set('al-tipoVehiculo', a.type);
      set('al-usuario', a.usuario);
      set('al-area', a.area);
      set('al-departamento', a.departamento);
      set('al-localidad', a.localidad);
      if (isNew) set('al-currentKm', a.currentKm);
      if (info) info.innerHTML = this.assetCard(a);
    } else {
      set('al-asset', '');
      set('al-tipoVehiculo', '');
      set('al-usuario', '');
      set('al-area', '');
      set('al-departamento', '');
      set('al-localidad', '');
      if (info) info.innerHTML = this.assetCard(null, search);
    }
    this.preview();
  },

  preview() {
    const g = eid => document.getElementById(eid)?.value || '';
    const p = this.compute(g('al-asset-search'), g('al-tipoVehiculo'), g('al-currentKm'), g('al-tipoMantenimiento'));
    const el = document.getElementById('al-nextkm');
    if (el) el.textContent = p.nextKm ? fmtKm(p.nextKm) : '—';
  },

  compute(vehiculo, tipoVehiculo, currentKm, tipoMantenimiento) {
    const intervaloKm = getAlertIntervalo(tipoVehiculo, tipoMantenimiento);
    const nextKm = intervaloKm ? getNextKm(currentKm, intervaloKm) : 0;
    return { intervaloKm, nextKm };
  },

    async save(id) {
    const g = eid => document.getElementById(eid)?.value?.trim();
    const assetId = g('al-asset');
    if (!assetId || !DB.getAsset(assetId)) {
      showToast('Seleccione un activo registrado antes de crear una alerta.', 'error');
      return;
    }
    const asset = DB.getAsset(assetId);

    const currentKm = parseFloat(g('al-currentKm')) || 0;
    const tipoMantenimiento = g('al-tipoMantenimiento');
    const fecha = g('al-fecha');
    const estado = g('al-estado') || 'Pendiente';

    if (!tipoMantenimiento) { showToast('El tipo de mantenimiento es obligatorio', 'error'); return; }
    if (!fecha) { showToast('La fecha de registro es obligatoria', 'error'); return; }

    const vehiculo     = asset.code;
    const tipoVehiculo = asset.type;
    const intervaloKm  = getAlertIntervalo(tipoVehiculo, tipoMantenimiento);
    const nextKm       = intervaloKm ? getNextKm(currentKm, intervaloKm) : 0;
    const remainingKm  = nextKm - currentKm;

    const data = {
      assetId, vehiculo, tipoVehiculo, currentKm, tipoMantenimiento, fecha, estado,
      usuario: asset.usuario || '', area: asset.area || '',
      departamento: asset.departamento || '', localidad: asset.localidad || '',
      placa: asset.plate || '', intervaloKm, nextKm, remainingKm,
      severity: getAlertSeverity({ estado, remainingKm, nextKm, currentKm }),
    };

    const session = Auth.getSession();
    if (id) {
      try {
        await DB.updateAlerta(id, data);
        DB.addAudit({ user: session?.name || '', action: 'UPDATE', detail: 'Alerta actualizada: ' + tipoMantenimiento + ' — ' + vehiculo });
        showToast('Alerta actualizada', 'success');
      } catch (e) {
        showToast(e.message || 'Error actualizando alerta', 'error');
        return;
      }
    } else {
      try {
        await DB.addAlerta(data);
        DB.addAudit({ user: session?.name || '', action: 'CREATE', detail: 'Alerta creada: ' + tipoMantenimiento + ' — ' + vehiculo });
        showToast('Alerta creada', 'success');
      } catch (e) {
        showToast(e.message || 'Error creando alerta', 'error');
        return;
      }
    }
    closeModal('alert-modal-placeholder');
    App.navigate('alerts');
  },

    async toggleEstado(id) {
    const a = DB.getAlertas().find(x => x.id === id);
    if (!a) return;
    try {
      await DB.updateAlerta(id, { estado: 'Completada' });
      DB.addAudit({ user: Auth.getSession()?.name || '', action: 'UPDATE', detail: 'Alerta completada: ' + a.tipoMantenimiento + ' — ' + a.vehiculo });
      showToast('Alerta marcada como completada', 'success');
      App.navigate('alerts');
    } catch (e) {
      showToast(e.message || 'Error actualizando alerta', 'error');
      return;
    }
  },

    async remove(id) {
    const a = DB.getAlertas().find(x => x.id === id);
    if (!a) return;
    if (!confirm('¿Eliminar esta alerta?')) return;
    try {
      await DB.deleteAlerta(id);
      try { localStorage.setItem('fleet_alerts_auto', '1'); } catch {}
      DB.addAudit({ user: Auth.getSession()?.name || '', action: 'DELETE', detail: 'Alerta eliminada: ' + a.tipoMantenimiento + ' — ' + a.vehiculo });
      showToast('Alerta eliminada', 'success');
      App.navigate('alerts');
    } catch (e) {
      showToast(e.message || 'Error eliminando alerta', 'error');
      return;
    }
  }
};

/* ====================================================
   ALERT ENGINE — integración con el dashboard principal
   (usa solo las alertas registradas, independiente de otros módulos)
   ==================================================== */
const AlertEngine = {
  generate() {
    return DB.getAlertas().map(a => ({
      ...a,
      severity: getAlertSeverity(a),
      remainingKm: parseFloat(a.remainingKm) || (parseFloat(a.nextKm) - parseFloat(a.currentKm)) || 0,
    }));
  },

  countBySeverity(alerts) {
    const list = Array.isArray(alerts) ? alerts : this.generate();
    return {
      danger:  list.filter(a => ['danger','critical'].includes(a.severity)).length,
      warning: list.filter(a => a.severity === 'warning').length,
      total:   list.filter(a => a.severity !== 'completed').length,
    };
  },

  TYPES: {
    OVERDUE:     { icon:'🚨', css:'alert-icon-danger',  label:'Vencido' },
    UPCOMING:    { icon:'⏰', css:'alert-icon-warning', label:'Próximo' },
    REPEAT_FAIL: { icon:'🔄', css:'alert-icon-danger',  label:'Falla Repetida' },
    INSPECTION:  { icon:'📜', css:'alert-icon-warning', label:'Inspección' },
  },
};

/* ── Formatting helpers (usados por otros módulos) ── */
function fmtDate(str) {
  if (!str) return '—';
  const d = new Date(String(str).length <= 10 ? str + 'T12:00:00' : str);
  return d.toLocaleDateString('es', { day:'2-digit', month:'2-digit', year:'numeric' });
}

function fmtCurrency(val) {
  const s = DB.getSettings();
  const sym = s.currency || 'Q';
  return `${sym} ${parseFloat(val||0).toLocaleString('es',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
}

function fmtNumber(val, dec=0) {
  return parseFloat(val||0).toLocaleString('es',{minimumFractionDigits:dec,maximumFractionDigits:dec});
}

function fmtHours(h) {
  h = parseFloat(h||0);
  if (h < 1) return `${Math.round(h*60)} min`;
  return `${h.toFixed(1)} hrs`;
}

function fmtKm(km) {
  return `${parseFloat(km||0).toLocaleString('es')} km`;
}

function daysDiff(dateStr) {
  const d = new Date(dateStr + 'T12:00:00');
  const now = new Date(); now.setHours(0,0,0,0);
  return Math.ceil((d - now) / 86400000);
}

function statusBadge(status) {
  const map = {
    operativo:     '<span class="badge badge-success">✅ Operativo</span>',
    mantenimiento: '<span class="badge badge-warning">🔧 Mantenimiento</span>',
    fuera:         '<span class="badge badge-danger">🔴 Fuera de Servicio</span>',
    done:          '<span class="badge badge-success">✅ Completado</span>',
    pending:       '<span class="badge badge-warning">⏳ Pendiente</span>',
    overdue:       '<span class="badge badge-danger">🚨 Vencido</span>',
    repaired:      '<span class="badge badge-success">✅ Reparado</span>',
    'in-progress': '<span class="badge badge-warning">🔧 En Proceso</span>',
  };
  return map[status] || `<span class="badge badge-muted">${status||'—'}</span>`;
}

function getAssetIcon(type) {
  const icons = {
    'Camión': '🚛', 'Montacarga': '🏗️', 'Cabezal': '🚚',
    'Remolque': '🚐', 'Tractor': '🚜', 'Generador': '⚡',
    'Vehículo': '🚗', 'Equipo Industrial': '⚙️',
  };
  return icons[type] || '🔧';
}

function getCategoryIcon(cat) {
  const icons = {
    combustible:'⛽', lubricantes:'🛢️', llantas:'🔵', baterias:'🔋',
    repuestos:'🔩', taller:'🏭', manodeobra:'👷', seguro:'🛡️',
    matricula:'📋', otros:'📌',
  };
  return icons[cat] || '💰';
}

function getCategoryLabel(cat) {
  const labels = {
    combustible:'Combustible', lubricantes:'Lubricantes', llantas:'Llantas',
    baterias:'Baterías', repuestos:'Repuestos', taller:'Taller Externo',
    manodeobra:'Mano de Obra', seguro:'Seguros', matricula:'Matrículas/Permisos', otros:'Otros',
  };
  return labels[cat] || cat;
}